name: Validate HTML files

on:
  push:
    paths:
      - '**.html'
  pull_request:
    paths:
      - '**.html'

jobs:
  html-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v0.4.0
        
